name: Publish new version kash

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Deploy new Version
        options:
          - kash library

permissions:
  contents: read

jobs:
  assets:
  
    name: 'Publish new version kash'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Add permission to run command gradle
        run: chmod +x ./gradlew

      - name: Generate new JAR output
        run: ./gradlew assemble

      - name: Publish new version in maven
        run: ./gradlew publish
        env:
          ENV_KASH_USERNAME: ${{ github.actor }}
          ENV_KASH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          
      
